name = "pdf2csv-worker"
main = "cf_worker.py"
compatibility_date = "2024-03-20"

# Enable the Python Workers Beta (Pyodide)
[build]
command = ""

[requirements]
# List the Python packages required by the worker
pymupdf = "1.23.26"
